/* National proposal-builder extension for the Enterprise Pricing Engine */
(() => {
  const cash = n => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',minimumFractionDigits:0}).format(n||0);
  let cart = [];
  const tpl = `
  <style>
  #proposal-launch{position:fixed;right:24px;bottom:24px;z-index:80;background:#f97316;color:#fff;border:0;border-radius:12px;padding:13px 17px;font:700 13px Inter,system-ui;box-shadow:0 10px 28px #f9731666;cursor:pointer}#proposal-launch:hover{background:#ea580c}.pb-back{display:none;position:fixed;inset:0;z-index:90;background:#0f172a99;padding:18px;align-items:center;justify-content:center}.pb-back.show{display:flex}.pb{width:min(1080px,100%);height:min(760px,94vh);background:#fff;border-radius:16px;overflow:hidden;display:grid;grid-template-rows:auto 1fr auto;box-shadow:0 20px 70px #02061777}.pb-head{padding:18px 22px;background:#071b35;color:#fff;display:flex;align-items:center;justify-content:space-between}.pb-head h2{margin:0;font-size:18px}.pb-head p{margin:4px 0 0;color:#9cc8e8;font-size:11px}.pb-close{border:0;background:transparent;color:#fff;font-size:24px;cursor:pointer}.pb-body{display:grid;grid-template-columns:1.1fr .9fr;min-height:0}.pb-choose{padding:18px;overflow:auto;border-right:1px solid #e2e8f0}.pb-cart{padding:18px;overflow:auto;background:#f8fafc}.pb-label{font-size:10px;font-weight:800;color:#64748b;letter-spacing:.6px;display:block;margin-bottom:5px}.pb-input,.pb-select{width:100%;border:1px solid #dbe4ed;border-radius:8px;padding:10px;outline-color:#1498e8;margin-bottom:12px}.pb-route{border:1px solid #e3eaf1;border-radius:10px;padding:12px;margin-bottom:8px;background:#fff}.pb-route-top{display:flex;justify-content:space-between;gap:8px;align-items:center}.pb-route b{font-size:12px;color:#0f2745}.pb-route small{color:#718096}.pb-route select{border:1px solid #dbe4ed;border-radius:6px;padding:6px;font-size:11px}.pb-add{background:#eaf7ff;color:#087cbd;border:1px solid #bfe4f8;border-radius:6px;padding:7px 9px;font-size:11px;font-weight:700;cursor:pointer}.pb-item{background:#fff;border:1px solid #e3eaf1;border-radius:9px;padding:11px;margin-bottom:8px}.pb-item h4{margin:0;font-size:12px}.pb-item p{margin:4px 0;color:#64748b;font-size:11px}.pb-remove{border:0;background:transparent;color:#dc2626;font-size:11px;font-weight:700;cursor:pointer}.pb-total{background:#071b35;color:#fff;border-radius:10px;padding:14px;margin-top:12px}.pb-total b{font-size:19px}.pb-foot{padding:14px 22px;border-top:1px solid #e2e8f0;display:flex;justify-content:space-between;align-items:center}.pb-btn{border:0;border-radius:8px;padding:10px 13px;font-size:12px;font-weight:700;cursor:pointer}.pb-btn.light{background:#eff6ff;color:#087cbd}.pb-btn.orange{background:#f97316;color:#fff}.pb-btn.dark{background:#071b35;color:#fff}@media(max-width:760px){.pb-body{grid-template-columns:1fr}.pb-cart{border-top:1px solid #e2e8f0}.pb{height:94vh}.pb-choose{border:0}.pb-foot{gap:7px;flex-wrap:wrap}}
  </style>
  <button id="proposal-launch">+ Pengajuan Penawaran</button>
  <div class="pb-back" id="pbBack"><div class="pb"><div class="pb-head"><div><h2>National Proposal Builder</h2><p>Pilih rute dan jenis armada, lalu gunakan rumus Enterprise Pricing Engine untuk surat penawaran.</p></div><button class="pb-close" id="pbClose">×</button></div><div class="pb-body"><section class="pb-choose"><label class="pb-label">NAMA KLIEN</label><input class="pb-input" id="pbClient" placeholder="Contoh: PT Astra International"><label class="pb-label">MARGIN TARGET (%)</label><input class="pb-input" id="pbMargin" type="number" min="0" value="20"><label class="pb-label">CARI RUTE</label><input class="pb-input" id="pbSearch" placeholder="Cari origin, tujuan, atau kilometer..."><div id="pbRoutes"></div></section><aside class="pb-cart"><label class="pb-label">RUTE & ARMADA TERPILIH</label><div id="pbCart"></div></aside></div><footer class="pb-foot"><span id="pbMeta" style="font-size:11px;color:#64748b">Belum ada rute dipilih</span><div><button class="pb-btn light" id="pbClear">Clear</button> <button class="pb-btn dark" id="pbExcel">Excel</button> <button class="pb-btn orange" id="pbPdf">PDF</button></div></footer></div></div>`;
  function boot() {
    if (typeof initialRoutes === 'undefined' || typeof initialFleets === 'undefined' || typeof calculatePricing === 'undefined') return;
    document.body.insertAdjacentHTML('beforeend', tpl);
    document.getElementById('proposal-launch').onclick = () => { pbBack.classList.add('show'); renderRoutes(); renderCart(); };
    pbClose.onclick = () => pbBack.classList.remove('show'); pbBack.onclick=e=>{if(e.target===pbBack)pbBack.classList.remove('show')};
    pbSearch.oninput=renderRoutes; pbMargin.oninput=renderCart; pbClear.onclick=()=>{cart=[];renderCart()}; pbExcel.onclick=excel;pbPdf.onclick=pdf;
  }
  function routeMatches() { const q=(pbSearch.value||'').toLowerCase(); return initialRoutes.filter(r=>(r.origin+' '+r.dest+' '+r.distanceKm).toLowerCase().includes(q)).slice(0,120); }
  function renderRoutes() { pbRoutes.innerHTML=routeMatches().map(r=>`<div class="pb-route"><div class="pb-route-top"><div><b>${r.origin} → ${r.dest}</b><br><small>${r.distanceKm} km · Tol ${cash(r.baseToll||0)}</small></div><button class="pb-add" onclick="pbAdd('${r.id}')">Add</button></div><div style="margin-top:8px"><select id="pbFleet-${r.id}">${initialFleets.map(f=>`<option value="${f.id}">${f.name}</option>`).join('')}</select></div></div>`).join('') || '<p style="font-size:12px;color:#718096">Rute tidak ditemukan.</p>'; }
  window.pbAdd = id => { const route=initialRoutes.find(r=>r.id===id), fleet=initialFleets.find(f=>f.id===document.getElementById('pbFleet-'+id).value); if(cart.some(x=>x.route.id===id&&x.fleet.id===fleet.id)){alert('Rute dan armada tersebut sudah ada di pengajuan.');return} cart.push({route,fleet});renderCart(); };
  function result(item){const margin=Number(pbMargin.value)||0;return calculatePricing(item.route,item.fleet,initialCosts,margin,margin);}
  function renderCart(){const total=cart.reduce((a,x)=>a+result(x).hargaJual,0);pbCart.innerHTML=cart.map((x,i)=>{const v=result(x);return `<div class="pb-item"><div class="pb-route-top"><h4>${x.route.origin} → ${x.route.dest}</h4><button class="pb-remove" onclick="pbRemove(${i})">Remove</button></div><p>${x.fleet.name} · ${x.route.distanceKm} km · Margin ${v.margin}%</p><b style="font-size:13px;color:#087cbd">${cash(v.hargaJual)}</b></div>`}).join('')+(cart.length?`<div class="pb-total"><small>TOTAL NILAI PENAWARAN</small><br><b>${cash(total)}</b></div>`:'<p style="font-size:12px;color:#718096">Pilih rute dan armada dari daftar di kiri.</p>');pbMeta.textContent=cart.length?`${cart.length} rute · Margin target ${pbMargin.value||0}% · ${cash(total)}`:'Belum ada rute dipilih';}
  window.pbRemove=i=>{cart.splice(i,1);renderCart()};
  function rows(){return cart.map((x,i)=>{const v=result(x);return {no:i+1,route:`${x.route.origin} - ${x.route.dest}`,km:x.route.distanceKm,fleet:x.fleet.name,hpp:v.totalHPP,margin:v.margin,sell:v.hargaJual};})}
  function excel(){const r=rows();if(!r.length)return alert('Pilih minimal satu rute.');if(!window.XLSX)return alert('Library Excel belum termuat.');const data=[['WHOOSH EXPRESS'],['SURAT PENAWARAN HARGA'],['Klien',pbClient.value||'-'],['Tanggal',new Date().toLocaleDateString('id-ID')],[],['No','Rute','KM','Armada','HPP','Margin %','Harga Penawaran'],...r.map(x=>[x.no,x.route,x.km,x.fleet,x.hpp,x.margin,x.sell]),[],['TOTAL','','','','','',r.reduce((a,x)=>a+x.sell,0)]];const ws=XLSX.utils.aoa_to_sheet(data);ws['!cols']=[{wch:7},{wch:38},{wch:10},{wch:20},{wch:18},{wch:12},{wch:20}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Surat Penawaran');XLSX.writeFile(wb,`WHOOSH-Penawaran-${Date.now()}.xlsx`)}
  function pdf(){const r=rows();if(!r.length)return alert('Pilih minimal satu rute.');if(!window.jspdf?.jsPDF)return alert('Library PDF belum termuat.');const doc=new window.jspdf.jsPDF({unit:'mm',format:'a4'});doc.setFillColor(7,27,53);doc.rect(0,0,210,30,'F');doc.setTextColor(255,255,255);doc.setFontSize(18);doc.text('WHOOSH EXPRESS',14,15);doc.setFontSize(10);doc.text('SURAT PENAWARAN HARGA',14,22);doc.setTextColor(20,41,62);doc.setFontSize(10);doc.text('Klien: '+(pbClient.value||'-'),14,42);doc.text('Tanggal: '+new Date().toLocaleDateString('id-ID'),14,48);doc.autoTable({startY:55,head:[['No','Rute','KM','Armada','Margin','Harga Penawaran']],body:r.map(x=>[x.no,x.route,x.km,x.fleet,x.margin+'%',cash(x.sell)]),foot:[['','','','','TOTAL',cash(r.reduce((a,x)=>a+x.sell,0))]],styles:{fontSize:8,cellPadding:3},headStyles:{fillColor:[7,27,53]},footStyles:{fillColor:[249,115,22]},columnStyles:{5:{halign:'right'}}});doc.setFontSize(8);doc.setTextColor(100,115,135);doc.text('Harga dihitung dengan Enterprise Pricing Engine: BBM, driver, transport, tol, operasional, asuransi, pajak, cadangan, dan margin.',14,doc.lastAutoTable.finalY+13);doc.save(`WHOOSH-Penawaran-${Date.now()}.pdf`)}
  window.addEventListener('load', boot);
})();
